const { depot } = require("@depot/sdk-node");
const { exec } = require("child_process");

const headers = {
  Authorization: `Bearer ${process.env.DEPOT_TOKEN}`,
};

async function runBuild(projectID) {
  const result = await depot.build.v1.BuildService.createBuild(
    {
      projectId: projectID,
    },
    { headers }
  );

  /*
    Execute Depot CLI binary to run build using the build ID and build token
    that were generated by the createBuild API call.
  */
  exec(
    "depot build --load .",
    {
      env: {
        DEPOT_PROJECT_ID: projectID,
        DEPOT_BUILD_ID: result.buildId,
        DEPOT_TOKEN: result.buildToken,
      },
    },
    (error, stdout, stderr) => {
      if (error) {
        console.error(`Error executing the binary: ${error}`);
        return;
      }

      console.log(`stdout:\n${stdout}`);
      console.error(`stderr:\n${stderr}`);
    }
  );
}

const projectID = args[0];

runBuild(projectID);
